### ISSUE TITLE
 SSL certificate problem

### ISSUE THREAD

**Issue by eydun** [wirecli/wire-cli#6]
When I try to "wirecli new" on my local machine, I get the error: ` Error loading sha master, curl request failed (status code: 0, url: https://raw.githubusercontent.com/processwire/processwire/master/wire/core/ProcessWire.php).
  cURL error: SSL certificate problem: unable to get local issuer certificate`

Does it perhaps a linux-installation? (I am using Windows)

**Comment by flydev-fr** [comment]
This is certainly due to the version of the **libcurl** delivered with your version of PHP. Without more details, you can try the following:

Open `php.ini` with a text editor, locate the section `[curl]`, check the value of the key `curl.cainfo`, if not empty, open the target directory from the value, rename the `cacert.pem` file and download the new one from https://curl.haxx.se/ca/cacert.pem then restart webserver/php.

Let me know if it worked, if not please add details about the PHP package you installed on Windows.

**Comment by flydev-fr** [comment]
That's what was intended, it's shorter to type; I made a mistake in the doc. But I'm thinking of adding an alias anyway.
